### ISSUE TITLE
Failed to activate the line-count-status package

### ISSUE THREAD

**Issue by iam-marixo** [olmokramer/atom-line-count-status#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [line-count-status](https://github.com/olmokramer/atom-line-count-status) package 0.0.3

### Stack Trace

Failed to activate the line-count-status package

```
At Cannot read property 'priority' of undefined

TypeError: Cannot read property 'priority' of undefined
    at StatusBarView.module.exports.StatusBarView.addLeftTile (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/status-bar/lib/status-bar-view.js:55:136)
    at Object.consumeStatusBarService (/packages/line-count-status/lib/line-count-status.js:22:29)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:690:42)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.21.1/resources/app/src/buffered-process.js:338:17)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.21.1/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  5x -6:44.9.0 intentions:highlight (input.hidden-input)
     -6:44.2.0 settings-view:open (input.hidden-input)
  4x -6:21.2.0 core:backspace (input.hidden-input)
  2x -6:19.9.0 core:confirm (input.hidden-input)
     -4:31.2.0 intentions:highlight (input.hidden-input)
     -4:30.9.0 settings-view:open (input.hidden-input)
  2x -1:57.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
angularjs 0.4.0 
atom-alignment 0.13.0 
atom-live-server 2.2.0 
atom-typescript 11.0.10 
auto-encoding 0.7.0 
auto-id-class 0.3.1 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-angular-material 0.4.0 
autocomplete-html-entities 0.1.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
chestnut-light-atom-syntax 0.2.1 
color-tabs 0.1.8 
css-from-html 0.1.5 
debug 0.0.1 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-simplified 2.5.0 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.13 
grammar-token-limit 0.1.1 
highlight-line 0.12.0 
html-head-snippets 0.2.0 
html-nested-comments 3.4.0 
html-to-css 0.2.2 
HTML2JS 0.2.1 
ide-purescript 0.19.1 
intentions 1.1.5 
language-purebasic 1.1.15 
line-count 0.5.0 
line-count-status 0.0.3 
linter 2.2.0 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
logo-file-icons 1.12.0 
minimap-pigments 0.2.2 
open-in-browser 0.5.2 
open-in-browsers 0.0.30 
pig 1.0.0 
pigments 0.40.2 
pure-syntax 0.3.0 
rainbow-delimiters 2.0.1 
scroll-through-time 0.2.0 
selection-counter 1.0.0 
seti-icons 1.5.4 
sloc 1.1.0 
theme-toggler 0.7.0 
toggle-gutter 0.3.3 
toggler 0.3.0 
webbox-color 0.5.9 
```

**Comment by olmokramer** [comment]
Hi @iam-marixo , I'm sorry for the extremely late reply. As you have probably noticed I've stopped maintaining my Atom plugins a few years ago. I got very frustrated with how Atom was maintained and started ignoring all of my plugins. I'm sorry for that. I won't install Atom to test and mergeer PRs, but I'd be happy to transfer my repositories to anyone that wants to maintain any of my plugins. Again, I'm sorry.
